name: Label Cherry Pick

on:
  pull_request_target:
    types:
      - labeled
      - closed

jobs:
  cherry_pick_23:
    runs-on: ubuntu-latest
    if: |
      contains(github.event.pull_request.labels.*.name, 'cp-23.lts.1+') &&
      github.event.pull_request.merged == true &&
      github.event.pull_request.merge_commit_sha != null
    env:
      ACCESS_TOKEN: ${{ secrets.CHERRY_PICK_TOKEN }}
      REPOSITORY: ${{ github.repository }}
      GITHUB_REF: ${{ github.ref }}
      MERGE_COMMIT_SHA: ${{ github.event.pull_request.merge_commit_sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
        with:
          ref: 23.lts.1+
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "GitHub Release Automation"
          git config --global user.email "github@google.com"

      - name: Cherry pick merge commit
        run: |
          git fetch origin 23.lts.1+
          git cherry-pick -x $MERGE_COMMIT_SHA

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@2b011faafdcbc9ceb11414d64d0573f37c774b04 # v4.2.3
        with:
          token: ${{ secrets.CHERRY_PICK_TOKEN }}
          base: 23.lts.1+
          branch: "23.lts.1+-${{ github.event.pull_request.number }}"
          committer: GitHub Release Automation <github@google.com>
          reviewers: ${{ github.event.pull_request.user.login }}
          title: "Cherry pick PR #${{ github.event.pull_request.number }}: ${{ github.event.pull_request.title }}"
          body: |
            "Refer to the original PR: https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}"
